spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      port: 0
      database: library
  batch:
    job:
      enabled: false
    initialize-schema: always

  shell:
    interactive:
      enabled: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local