spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: library

  mvc.hiddenmethod.filter.enabled: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local