spring:
  data:
    mongodb:
      port: 0
      database: library

  mvc.hiddenmethod.filter.enabled: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

#    show-sql: true

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true