spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  mvc.hiddenmethod.filter.enabled: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  health:
    defaults:
      enabled: true

info:
  version: @project.version@
  author: vadony
  description: Vadoniy's electronic library on Otus Spring Framework learning course