spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  mvc.hiddenmethod.filter.enabled: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,logfile,health
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  health:
    defaults:
      enabled: true

info:
  version: @project.version@
  author: vadony
  description: Vadoniy's electronic library on Otus Spring Framework learning course

logging:
  file:
    max-history: 10
    max-size: 10MB
    name: logs/vadony-library.log
  level:
    org.springframework: INFO
    otus.rest: DEBUG