INSERT INTO AUTHOR (NAME) VALUES ('Jennings Gary'), ('Glukhovskiy Dmitriy'), ('Joanne Rowling');

INSERT INTO GENRE (GENRE) VALUES ('NOVEL'), ('FANTASY'), ('NON FICTION');

INSERT INTO BOOK (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Metro 2033', 2, 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Aztec', 1, 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Harry Potter', 3, 2);

INSERT INTO COMMENT (COMMENT, OWNER, BOOK_ID) VALUES ('Like it was yesterday', 'Mikstly', 2);
INSERT INTO COMMENT (COMMENT, OWNER, BOOK_ID) VALUES ('I wanted to help!', 'Black_One', 1);
INSERT INTO COMMENT (COMMENT, OWNER, BOOK_ID) VALUES ('Mischief Managed!', 'Harry1997', 3);